import { z } from 'zod';
import {
  enemySchema,
  heroStatsSchema,
  progressionSchema,
  stageSchema,
} from '../game/progression.contract.js';
import { hugeAmountSchema } from '../huge-number/huge-number.contract.js';
import { characterSchema } from '../player/player.contract.js';
import { stageNumberSchema } from '../stage/stage-number.contract.js';

/**
 * `POST /player/characters/:characterId/combats` — resolve the character's
 * next combat on the server (ADR-019).
 *
 * The request has no body. Everything that decides the combat — stage, enemy,
 * stats, seed, outcome and rewards — is determined by the server. The client
 * sends only the character it targets (path) and an idempotency key (header).
 */

/**
 * Header naming one player intent to fight. Retrying with the same key
 * returns the same combat and never grants its rewards twice.
 */
export const IDEMPOTENCY_KEY_HEADER = 'Idempotency-Key';

/** A UUID generated by the client per intent. It carries no gameplay input. */
export const idempotencyKeySchema = z.uuid();

export const combatOutcomeSchema = z.enum(['WIN', 'LOSS']);
export type CombatOutcomeDto = z.infer<typeof combatOutcomeSchema>;

export const combatEndReasonSchema = z.enum(['ENEMY_DEFEATED', 'PLAYER_DEFEATED', 'TIME_LIMIT']);
export type CombatEndReasonDto = z.infer<typeof combatEndReasonSchema>;

/** One resolved attack, in the order Game Core resolved it. */
export const combatEventSchema = z.object({
  /** Milliseconds from the start of the combat. */
  timeMs: z.number().int().min(0),
  attacker: z.enum(['PLAYER', 'ENEMY']),
  critical: z.boolean(),
  damage: hugeAmountSchema,
  /** The defender's health after this hit, never below zero. */
  targetHealth: hugeAmountSchema,
});
export type CombatEventDto = z.infer<typeof combatEventSchema>;

export const rewardsSchema = z.object({
  gold: hugeAmountSchema,
  experience: hugeAmountSchema,
});
export type RewardsDto = z.infer<typeof rewardsSchema>;

/** Progression at one instant: before or after the combat. */
export const progressSnapshotSchema = z.object({
  level: z.number().int().min(1),
  experience: hugeAmountSchema,
  experienceToNextLevel: hugeAmountSchema,
  gold: hugeAmountSchema,
  stage: stageNumberSchema,
});
export type ProgressSnapshotDto = z.infer<typeof progressSnapshotSchema>;

export const combatSchema = z.object({
  id: z.uuid(),
  stage: stageSchema,
  enemy: enemySchema,
  /** The hero as it fought: stats from its level before the combat. */
  hero: heroStatsSchema,
  outcome: combatOutcomeSchema,
  endReason: combatEndReasonSchema,
  durationMs: z.number().int().min(0),
  /** Bounded by the rule set's time limit and attack-speed cap. */
  events: z.array(combatEventSchema).max(1_000),
  /** Zero for a loss. */
  rewards: rewardsSchema,
  levelsGained: z.number().int().min(0),
  resolvedAt: z.iso.datetime(),
});
export type CombatDto = z.infer<typeof combatSchema>;

export const combatResponseSchema = z.object({
  combat: combatSchema,
  before: progressSnapshotSchema,
  after: progressSnapshotSchema,
  /** The character's state after this combat. */
  character: characterSchema,
  /** Derived values after this combat, including the next encounter. */
  progression: progressionSchema,
  serverTime: z.iso.datetime(),
});
export type CombatResponse = z.infer<typeof combatResponseSchema>;
